repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      args: [-v]
  - repo: https://gitlab.com/pycqa/flake8 
    rev: 3.8.1
    hooks:
    - id: flake8
