repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      args: [-v]
  - repo: https://gitlab.com/pycqa/flake8 
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-docstrings>=1.5.0', 
        'flake8-rst-docstrings>=0.0.14',
        'flake8-bugbear>=20.11.1',
        'pep8-naming>=0.11.1',
      ]
